### ISSUE TITLE
Difficulty with NPM Dependency Changes When Switching Branches

### ISSUE THREAD

**Issue by aofn** [medienhaus/medienhaus-docker-dev#2]
When switching between Git branches that have different npm dependencies, it requires some manual actions in order to work. I am not sure if this can be automated, so if not feel free to mark as `wontfix` and/or close.

**Steps to Reproduce:**

1.  Attempt to start the Docker environment without any additional steps.than the current branch.
2. Checkout a branch with different npm dependencies 

**Expected Behavior:**

Switching branches should ideally not require additional steps to clean Docker volumes or delete specific images to ensure the proper functioning of the Docker setup.

**Current Behavior:**

The Docker environment encounters issues due to differences in npm dependencies, requiring the execution of the following commands to work correctly:

- `docker-compose down --volumes`
- Deletion of the `medienhaus-docker-dev-medienhaus-spaces:latest` image
- `docker-compose up -d`

**Comment by andirueckel** [comment]
Not sure we can fix this via `medienhaus-docker-dev`.

There’s [`docker compose watch`](https://docs.docker.com/compose/file-watch/), but unfortunately this does not seem to work with bind mounts.

```
$ cat docker-compose.yml
[…]
  medienhaus-spaces:
    build:
      context: ./medienhaus-spaces
      target: "development-runner"
    develop:
      watch:
        - action: sync
          path: ./medienhaus-spaces
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./medienhaus-spaces/package.json
          target: /app/package.json
    […]
    volumes:
      - ./config/medienhaus-spaces.config.js:/app/config.js:ro
      - ./medienhaus-spaces:/app:rw
      […]
[…]
```

```
$ docker compose watch
[…]
WARN[0000] path '/path/to/medienhaus-docker-dev/medienhaus-spaces' also declared by a bind mount volume, this path won't be monitored!
WARN[0000] path '/path/to/medienhaus-docker-dev/medienhaus-spaces/package.json' also declared by a bind mount volume, this path won't be monitored!
watching []
```

If I remember correctly, the bind mount is necessary for the hot-reloading feature inside `medienhaus-spaces/` when making local code changes during development and testing, @fnwbr?

PS: The same applies to [`medienhaus-docker`](https://github.com/medienhaus/medienhaus-docker) and [`medienhaus-spaces/docker-compose.yml`](https://github.com/medienhaus/medienhaus-spaces/blob/main/docker-compose.yml).

> The Docker environment encounters issues due to differences in npm dependencies, requiring the execution of the following commands to work correctly:
> 
> - `docker-compose down --volumes`
> - Deletion of the `medienhaus-docker-dev-medienhaus-spaces:latest` image
> - `docker-compose up -d`

@marcel-klasse Not a fix, but you could run the following command(s) instead of manually deleting the local image:

```
docker compose down --volumes medienhaus-spaces && \
docker compose up -d --force-recreate --build --no-deps medienhaus-spaces
```
